controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

contact_send:
    path: '/contact/send'
    controller: 'App\Controller\ContactController::sendContactForm'
    methods: ['POST']
